import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/ui/header/header'
import Footer from '@/components/ui/footer/footer'
import Wrapper from "@/components/wrapper"
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang="en">
      <body className="bg-brand-white-100 font-family-inter dark:bg-brand-black-900 dark:text-brand-white-100 text-brand-black-1000">
        <Header />
        <Wrapper>
          {children}
        </Wrapper>
        <Footer />
      </body>
    </html>
  )
}