import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/ui/header";
import DarkModeToggle from "@/components/ui/dark-mode-toggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-brand-white-light dark:bg-brand-pureblack dark:text-brand-white-regular text-brand-black-regular">
        <Header />
        {children}
      </body>
    </html>
  );
}